[package]
name = "json-flat-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simdutf8 = { version = "0.1.4", optional = true }

[features]
simdutf8 = ["dep:simdutf8"]
